CREATE TABLE AFB0660
(
	CASEID CHAR    (9) NOT NULL DEFAULT ' ' ,
	CASETYPE CHAR    (2) NOT NULL DEFAULT ' ' ,
	POLICYID CHAR    (11) NOT NULL DEFAULT ' ' ,
	ARRVALDATE NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	FROMQUE CHAR    (10) NOT NULL DEFAULT ' ' ,
	TOQUE CHAR    (10) NOT NULL DEFAULT ' ' ,
	USERID CHAR    (10) NOT NULL DEFAULT ' ' ,
	CURDATE NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	CURTIME NUMERIC (8, 0) NOT NULL DEFAULT 0
);

CREATE TABLE AFBAPIERR
(
	AFBPGM CHAR    (10) NOT NULL DEFAULT ' ' ,
	USERID CHAR    (10) NOT NULL DEFAULT ' ' ,
	DATEIN DATE     NOT NULL DEFAULT CAST(CAST(GETDATE() AS DATE) AS DATETIME) ,
	TIMEIN time(0)  NOT NULL DEFAULT   cast (getdate() as time (0)),
	WAFPGM CHAR    (10) NOT NULL DEFAULT ' ' ,
	RETCOD NUMERIC (6, 0) NOT NULL DEFAULT 0 ,
	STATUS CHAR    (6) NOT NULL DEFAULT ' ' ,
	TEXT CHAR    (100) NOT NULL DEFAULT ' '
);

CREATE TABLE AFFCLIENT
(
	ACAFFCODE CHAR    (8) NOT NULL DEFAULT ' ' ,
	ACCLIENTID CHAR    (15) NOT NULL DEFAULT ' '
);

CREATE TABLE AUTOCMTPF
(
	CMTID CHAR    (4) NOT NULL DEFAULT ' ' ,
	CMTTEXT CHAR    (75) NOT NULL DEFAULT ' ' ,
	ID3NOTE CHAR    (1) NOT NULL DEFAULT ' '
);

CREATE TABLE BAEDHST
(
	HAFBCASENO CHAR    (12) NOT NULL DEFAULT ' ' ,
	HLPOCASENO CHAR    (12) NOT NULL DEFAULT ' ' ,
	HPOLTYPE CHAR    (3) ,
	HSSN CHAR    (9) ,
	HLNAME CHAR    (30) ,
	HFNAME CHAR    (20) ,
	HMINIT CHAR    (1)
);

CREATE TABLE BAENDORSE
(
	AFBCASENO CHAR    (12) NOT NULL DEFAULT ' ' ,
	LPOCASENO CHAR    (12) NOT NULL DEFAULT ' ' ,
	POLTYPE CHAR    (3) ,
	SSN CHAR    (9) ,
	LNAME CHAR    (30) ,
	FNAME CHAR    (20) ,
	MINIT CHAR    (1)
);

CREATE TABLE BPAYRC
(
	RC CHAR    (1) NOT NULL DEFAULT ' ' ,
	RCTEXT CHAR    (75) NOT NULL DEFAULT ' '
);

CREATE TABLE CCSSNREL
(
	CSCASEID CHAR    (9) NOT NULL DEFAULT ' ' ,
	CSDOCID CHAR    (12) NOT NULL DEFAULT ' ' ,
	CSPAYSSN NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	CSPRODSEL CHAR    (1) NOT NULL DEFAULT ' ' ,
	CSPOLID CHAR    (11) NOT NULL DEFAULT ' ' ,
	CSPOLTYPE CHAR    (4) NOT NULL DEFAULT ' ' ,
	CSTEMPLNAM CHAR    (10) NOT NULL DEFAULT ' ' ,
	CSRECUR CHAR    (1) NOT NULL DEFAULT ' ' ,
	CSPREMAMT NUMERIC (7, 2) NOT NULL DEFAULT 0 ,
	CSRETCODE CHAR    (1) NOT NULL DEFAULT ' ' ,
	CSTRANSID CHAR    (8) NOT NULL DEFAULT ' '
);

CREATE TABLE CODESFL
(
	SYS_CODETYPE CHAR    (10) NOT NULL DEFAULT ' ' ,
	SYS_CODE CHAR    (10) NOT NULL DEFAULT ' ' ,
	SYS_CODEDATE NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	SYS_CODEDESC CHAR    (30) NOT NULL DEFAULT ' ' ,
	SYS_CODEBUFF CHAR    (30) NOT NULL DEFAULT ' '
);

CREATE TABLE DDAPPS
(
	TRANSID CHAR    (8) NOT NULL DEFAULT ' ' ,
	TEMPLNAME CHAR    (10) NOT NULL DEFAULT ' ' ,
	NBROFPAGES NUMERIC (2, 0) NOT NULL DEFAULT 0 ,
	PROCESSFLG CHAR    (1) NOT NULL DEFAULT ' ' ,
	PRODTYPE CHAR    (1) NOT NULL DEFAULT ' ' ,
	MBRSSN NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	SPONRANK CHAR    (8) NOT NULL DEFAULT ' ' ,
	SPONLNAME CHAR    (28) NOT NULL DEFAULT ' ' ,
	SPONFNAME CHAR    (20) NOT NULL DEFAULT ' ' ,
	SPONMNAME CHAR    (1) NOT NULL DEFAULT ' ' ,
	SPONSSN NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	COVEFFDATE NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	AGTCODE CHAR    (8) NOT NULL DEFAULT ' ' ,
	AGTCODE2 CHAR    (8) NOT NULL DEFAULT ' ' ,
	AGTPCT1 NUMERIC (2, 0) NOT NULL DEFAULT 0 ,
	AGTPCT2 NUMERIC (2, 0) NOT NULL DEFAULT 0 ,
	AGTMKTCODE CHAR    (10) NOT NULL DEFAULT ' ' ,
	AGTLVL CHAR    (2) NOT NULL DEFAULT ' ' ,
	AFFCODE CHAR    (8) NOT NULL DEFAULT ' ' ,
	DEPLFLAG CHAR    (1) NOT NULL DEFAULT ' ' ,
	PAYROLLNBR CHAR    (6) NOT NULL DEFAULT ' ' ,
	ATTCHFLAG CHAR    (1) NOT NULL DEFAULT ' ' ,
	PREMPAID NUMERIC (7, 2) NOT NULL DEFAULT 0 ,
	NBRATTCH NUMERIC (2, 0) NOT NULL DEFAULT 0 ,
	PLANTYPE CHAR    (1) NOT NULL DEFAULT ' ' ,
	POSCASENBR CHAR    (8) NOT NULL DEFAULT ' ' ,
	RPLTYPE CHAR    (1) NOT NULL DEFAULT ' ' ,
	RANK CHAR    (8) NOT NULL DEFAULT ' ' ,
	MBRLNAME CHAR    (28) NOT NULL DEFAULT ' ' ,
	MBRFNAME CHAR    (20) NOT NULL DEFAULT ' ' ,
	MBRMINIT CHAR    (1) NOT NULL DEFAULT ' ' ,
	MBRSPFLAG CHAR    (1) NOT NULL DEFAULT ' ' ,
	MBRDOB NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	MBRHEIGHT NUMERIC (3, 0) NOT NULL DEFAULT 0 ,
	MBRWEIGHT NUMERIC (3, 0) NOT NULL DEFAULT 0 ,
	MBRELIGIB CHAR    (1) NOT NULL DEFAULT ' ' ,
	MBRDUTYSTT CHAR    (1) NOT NULL DEFAULT ' ' ,
	ACTIVATEFG CHAR    (1) NOT NULL DEFAULT ' ' ,
	MARRYIND CHAR    (1) NOT NULL DEFAULT ' ' ,
	ESPGOVIND CHAR    (1) NOT NULL DEFAULT ' ' ,
	MBRSEX CHAR    (1) NOT NULL DEFAULT ' ' ,
	MBRSMOKER CHAR    (1) NOT NULL DEFAULT ' ' ,
	MBRADDR1 CHAR    (30) NOT NULL DEFAULT ' ' ,
	MBRADDR2 CHAR    (30) NOT NULL DEFAULT ' ' ,
	MBRCITY CHAR    (27) NOT NULL DEFAULT ' ' ,
	MBRSTATE CHAR    (2) NOT NULL DEFAULT ' ' ,
	MBRZIP NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	MBREMAIL CHAR    (50) NOT NULL DEFAULT ' ' ,
	MBRDPHONE CHAR    (10) NOT NULL DEFAULT ' ' ,
	MBREPHONE CHAR    (10) NOT NULL DEFAULT ' ' ,
	MBRPOBST CHAR    (2) NOT NULL DEFAULT ' ' ,
	MBRPOBCNTR CHAR    (16) NOT NULL DEFAULT ' ' ,
	MBRCITIZEN CHAR    (1) NOT NULL DEFAULT ' ' ,
	SPSSN NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	SPLNAME CHAR    (28) NOT NULL DEFAULT ' ' ,
	SPFNAME CHAR    (20) NOT NULL DEFAULT ' ' ,
	SPMINIT CHAR    (1) NOT NULL DEFAULT ' ' ,
	SPDOB NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	SPHEIGHT NUMERIC (3, 0) NOT NULL DEFAULT 0 ,
	SPWEIGHT NUMERIC (3, 0) NOT NULL DEFAULT 0 ,
	SPSEX CHAR    (1) NOT NULL DEFAULT ' ' ,
	SPSMOKER CHAR    (1) NOT NULL DEFAULT ' ' ,
	APPSTATE CHAR    (2) NOT NULL DEFAULT ' ' ,
	SSLICOVTYP CHAR    (1) NOT NULL DEFAULT ' ' ,
	SSLICOVAMT NUMERIC (3, 0) NOT NULL DEFAULT 0 ,
	SSLIFAMTYP CHAR    (1) NOT NULL DEFAULT ' ' ,
	EMPTAXID NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	OWNERSSN NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	OWNERFNAME CHAR    (20) NOT NULL DEFAULT ' ' ,
	OWNERLNAME CHAR    (28) NOT NULL DEFAULT ' ' ,
	OWNERADDR1 CHAR    (30) NOT NULL DEFAULT ' ' ,
	OWNERCITY CHAR    (27) NOT NULL DEFAULT ' ' ,
	OWNERSTATE CHAR    (2) NOT NULL DEFAULT ' ' ,
	OWNERZIP NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	OWNERREL CHAR    (3) NOT NULL DEFAULT ' ' ,
	OWNERPHONE CHAR    (10) NOT NULL DEFAULT ' ' ,
	OWNEREMAIL CHAR    (50) NOT NULL DEFAULT ' ' ,
	PAYORIND CHAR    (1) NOT NULL DEFAULT ' ' ,
	PAYORSSN NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	PAYORFNAME CHAR    (20) NOT NULL DEFAULT ' ' ,
	PAYORLNAME CHAR    (28) NOT NULL DEFAULT ' ' ,
	PAYORADDR1 CHAR    (30) NOT NULL DEFAULT ' ' ,
	PAYORCITY CHAR    (27) NOT NULL DEFAULT ' ' ,
	PAYORSTATE CHAR    (2) NOT NULL DEFAULT ' ' ,
	PAYORZIP NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	PAYORREL CHAR    (3) NOT NULL DEFAULT ' ' ,
	PAYORPHONE CHAR    (10) NOT NULL DEFAULT ' ' ,
	CONTOWNER CHAR    (1) NOT NULL DEFAULT ' ' ,
	EXRBENELTR CHAR    (1) NOT NULL DEFAULT ' ' ,
	AGTRPLIND CHAR    (1) NOT NULL DEFAULT ' ' ,
	RPLIND CHAR    (1) NOT NULL DEFAULT ' ' ,
	INITPAYMNT CHAR    (1) NOT NULL DEFAULT ' ' ,
	PAYMODE CHAR    (1) NOT NULL DEFAULT ' ' ,
	PAYMODEEXT CHAR    (1) NOT NULL DEFAULT ' ' ,
	LSTBILLFRQ CHAR    (1) NOT NULL DEFAULT ' ' ,
	MBRPREM NUMERIC (5, 2) NOT NULL DEFAULT 0 ,
	SPPREM NUMERIC (5, 2) NOT NULL DEFAULT 0 ,
	CHILDPREM NUMERIC (3, 2) NOT NULL DEFAULT 0 ,
	MBRTOTPREM NUMERIC (5, 2) NOT NULL DEFAULT 0 ,
	MBRCOVUNIT NUMERIC (4, 0) NOT NULL DEFAULT 0 ,
	IPCOVUNIT NUMERIC (6, 3) NOT NULL DEFAULT 0 ,
	SPCOVUNIT NUMERIC (3, 0) NOT NULL DEFAULT 0 ,
	LOANPREFLG CHAR    (1) NOT NULL DEFAULT ' ' ,
	IPPREM NUMERIC (6, 2) NOT NULL DEFAULT 0 ,
	CHILDIND CHAR    (1) NOT NULL DEFAULT ' ' ,
	CHILDUNIT NUMERIC (1, 0) NOT NULL DEFAULT 0 ,
	ELECISSFLG CHAR    (1) NOT NULL DEFAULT ' ' ,
	MBRB1FNAME CHAR    (20) NOT NULL DEFAULT ' ' ,
	MBRB1LNAME CHAR    (28) NOT NULL DEFAULT ' ' ,
	MBRB1REL CHAR    (3) NOT NULL DEFAULT ' ' ,
	MBRB1SSN NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	MBRB1DOB NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	MBRB1SEX CHAR    (1) NOT NULL DEFAULT ' ' ,
	MBRBPCT1 NUMERIC (3, 0) NOT NULL DEFAULT 0 ,
	MBRB2FNAME CHAR    (20) NOT NULL DEFAULT ' ' ,
	MBRB2LNAME CHAR    (28) NOT NULL DEFAULT ' ' ,
	MBRB2REL CHAR    (3) NOT NULL DEFAULT ' ' ,
	MBRB2SSN NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	MBRB2DOB NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	MBRBPCT2 NUMERIC (3, 0) NOT NULL DEFAULT 0 ,
	SPBFNAME CHAR    (20) NOT NULL DEFAULT ' ' ,
	SPBLNAME CHAR    (28) NOT NULL DEFAULT ' ' ,
	SPBREL CHAR    (3) NOT NULL DEFAULT ' ' ,
	SPBSSN NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	SPBDOB NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	CHDBFNAME CHAR    (20) NOT NULL DEFAULT ' ' ,
	CHDBLNAME CHAR    (28) NOT NULL DEFAULT ' ' ,
	CHDBREL CHAR    (3) NOT NULL DEFAULT ' ' ,
	CHDBSSN NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	CHDBDOB NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	MBRHQ CHAR    (30) NOT NULL DEFAULT ' ' ,
	CHILDHQ CHAR    (30) NOT NULL DEFAULT ' ' ,
	SPHQ CHAR    (10) NOT NULL DEFAULT ' ' ,
	MBRHQINIT CHAR    (4) NOT NULL DEFAULT ' ' ,
	GNALNOTE CHAR    (1) NOT NULL DEFAULT ' ' ,
	GNALNOTE1 CHAR    (1) NOT NULL DEFAULT ' ' ,
	MBRSIGNFLG CHAR    (1) NOT NULL DEFAULT ' ' ,
	MBRSIGNDAT NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	SPSIGNFLG CHAR    (1) NOT NULL DEFAULT ' ' ,
	SPSIGNDAT NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	PAYSIGNFLG CHAR    (1) NOT NULL DEFAULT ' ' ,
	PAYSIGNDAT NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	OWNSIGNFLG CHAR    (1) NOT NULL DEFAULT ' ' ,
	OWNSIGNDAT NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	CNTRCITY CHAR    (27) NOT NULL DEFAULT ' ' ,
	CNTRSTATE CHAR    (2) NOT NULL DEFAULT ' ' ,
	XREFSSN NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	BTMFROM CHAR    (4) NOT NULL DEFAULT ' ' ,
	BTMFRMAMPM CHAR    (1) NOT NULL DEFAULT ' ' ,
	BTMTO CHAR    (4) NOT NULL DEFAULT ' ' ,
	BTMTOAMPM CHAR    (1) NOT NULL DEFAULT ' ' ,
	BDAY CHAR    (1) NOT NULL DEFAULT ' ' ,
	BDAYAMPM CHAR    (1) NOT NULL DEFAULT ' ' ,
	PARAMEDI CHAR    (1) NOT NULL DEFAULT ' ' ,
	AGTSIGNFLG CHAR    (1) NOT NULL DEFAULT ' ' ,
	AGTSIGNDAT NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	AGENTNOTE CHAR    (1) NOT NULL DEFAULT ' ' ,
	ENTRYDATE NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	ENTRYTIME NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	LSTCHGDATE NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	LSTCHGTIME NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	MKTCAMPGN CHAR    (50) NOT NULL DEFAULT ' ' ,
	ELCISSUE CHAR    (1) NOT NULL DEFAULT ' ' ,
	DUMMYFLD CHAR    (10) NOT NULL DEFAULT ' ' ,
	LT121IND CHAR    (1) NOT NULL DEFAULT ' ' ,
	DEPTCODE CHAR    (10) NOT NULL DEFAULT ' ' ,
	SPEMPFLAG CHAR    (1) NOT NULL DEFAULT ' ' ,
	SUVBENFLG CHAR    (1) NOT NULL DEFAULT ' ' ,
	CBSCHFLG CHAR    (1) NOT NULL DEFAULT ' '
);

CREATE TABLE DDATTACH
(
	TRANSID CHAR    (8) NOT NULL DEFAULT ' ' ,
	TEMPLNAME CHAR    (10) NOT NULL DEFAULT ' ' ,
	PROCESSFLG CHAR    (1) NOT NULL DEFAULT ' ' ,
	NBROFPAGES NUMERIC (2, 0) NOT NULL DEFAULT 0 ,
	APPLFLAG CHAR    (1) NOT NULL DEFAULT ' ' ,
	ENTRYDATE NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	ENTRYTIME NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	LSTCHGDATE NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	LSTCHGTIME NUMERIC (8, 0) NOT NULL DEFAULT 0
);

CREATE TABLE DDCHECK
(
	TRANSID CHAR    (8) NOT NULL DEFAULT ' ' ,
	TEMPLNAME CHAR    (10) NOT NULL DEFAULT ' ' ,
	NBROFPAGES NUMERIC (2, 0) NOT NULL DEFAULT 0 ,
	INSSSN1 NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	INSSSN2 NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	INSSSN3 NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	INSSSN4 NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	INSSSN5 NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	INSSSN6 NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	INSSSN7 NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	INSSSN8 NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	PROCESSFLG CHAR    (1) NOT NULL DEFAULT ' ' ,
	FUTUREDATE NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	LASTNAME CHAR    (28) NOT NULL DEFAULT ' ' ,
	FIRSTNAME CHAR    (20) NOT NULL DEFAULT ' ' ,
	MINIT CHAR    (1) NOT NULL DEFAULT ' ' ,
	PAYORSSN NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	ADDR1 CHAR    (30) NOT NULL DEFAULT ' ' ,
	ADDR2 CHAR    (30) NOT NULL DEFAULT ' ' ,
	CITY CHAR    (27) NOT NULL DEFAULT ' ' ,
	STATE CHAR    (2) NOT NULL DEFAULT ' ' ,
	ZIPCODE NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	RTNNBR NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	BILLDAY CHAR    (2) NOT NULL DEFAULT ' ' ,
	ACCTTYPE CHAR    (1) NOT NULL DEFAULT ' ' ,
	ACCTNBR CHAR    (17) NOT NULL DEFAULT ' ' ,
	SIGNFLAG CHAR    (1) NOT NULL DEFAULT ' ' ,
	SIGNDATE NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	ENTRYDATE NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	ENTRYTIME NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	LSTCHGDATE NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	LSTCHGTIME NUMERIC (8, 0) NOT NULL DEFAULT 0
);

CREATE TABLE DDCREDIT
(
	TRANSID CHAR    (8) NOT NULL DEFAULT ' ' ,
	TEMPLNAME CHAR    (10) NOT NULL DEFAULT ' ' ,
	NBROFPAGES NUMERIC (2, 0) NOT NULL DEFAULT 0 ,
	INSSSN1 NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	INSSSN2 NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	INSSSN3 NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	INSSSN4 NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	INSSSN5 NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	INSSSN6 NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	INSSSN7 NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	INSSSN8 NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	PAYORSSN NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	PROCESSFLG CHAR    (1) NOT NULL DEFAULT ' ' ,
	FUTUREDATE NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	LASTNAME CHAR    (28) NOT NULL DEFAULT ' ' ,
	FIRSTNAME CHAR    (20) NOT NULL DEFAULT ' ' ,
	MINIT CHAR    (1) NOT NULL DEFAULT ' ' ,
	ACCTNBR CHAR    (16) NOT NULL DEFAULT ' ' ,
	BILLDAY CHAR    (2) NOT NULL DEFAULT ' ' ,
	EXPDATE NUMERIC (6, 0) NOT NULL DEFAULT 0 ,
	SIGNFLAG CHAR    (1) NOT NULL DEFAULT ' ' ,
	ENTRYDATE NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	ENTRYTIME NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	LSTCHGDATE NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	LSTCHGTIME NUMERIC (8, 0) NOT NULL DEFAULT 0
);

CREATE TABLE DOCMOVE
(
	MDOCTYPE CHAR    (4) NOT NULL DEFAULT ' ',
	MCASENUM CHAR    (2) NOT NULL DEFAULT ' '
);

CREATE TABLE DOCTEMP
(
	TEMP_DOC_TYPE CHAR    (8) NOT NULL DEFAULT ' ' ,
	TEMP_MONTHS NUMERIC (2, 0) NOT NULL DEFAULT 0
);

CREATE TABLE FINTRGTQ
(
	POLID CHAR    (11) NOT NULL DEFAULT ' ' ,
	QUEID CHAR    (10) NOT NULL DEFAULT ' '
);

CREATE TABLE ICRFILE
(
	DOC_ID CHAR    (12) NOT NULL DEFAULT ' ' ,
	TEMPL_NAME CHAR    (10) NOT NULL DEFAULT ' ' ,
	ACCOUNT_ID CHAR    (20) NOT NULL DEFAULT ' ' ,
	ICR_BUFFER CHAR    (1358) NOT NULL DEFAULT ' '
);

CREATE TABLE ID3REJECT
(
	SSN_NO NUMERIC (9, 0) NOT NULL DEFAULT 0 ,
	POL_CODE CHAR    (4) NOT NULL DEFAULT ' ' ,
	REJ_CAUSE_CODE CHAR    (8) NOT NULL DEFAULT ' ' ,
	REJ_DATE CHAR    (8) NOT NULL DEFAULT ' ' ,
	REAPP_DATE CHAR    (8) NOT NULL DEFAULT ' ' ,
	AUDT_DATE CHAR    (8) NOT NULL DEFAULT ' ' ,
	REF_CONT_NO CHAR    (10) NOT NULL DEFAULT ' ' ,
	REF_USER_ID CHAR    (10) NOT NULL DEFAULT ' ' ,
	REF_COMENT CHAR    (30) NOT NULL DEFAULT ' ' ,
	REF_COMENT2 CHAR    (80) NOT NULL DEFAULT ' '
);

CREATE TABLE LIFEAGT
(
	LAGTNUM CHAR    (12) NOT NULL DEFAULT ' ' ,
	LSTATE CHAR    (2) NOT NULL DEFAULT ' ' ,
	LMTATUS CHAR    (1) NOT NULL DEFAULT ' ' ,
	LSTATUS CHAR    (1) NOT NULL DEFAULT ' ' ,
	LEXPDATE NUMERIC (8, 0) NOT NULL DEFAULT 0
);

CREATE TABLE LPAUTOISS
(
	LPPOLID CHAR    (10) NOT NULL DEFAULT ' ' ,
	LPDOCID CHAR    (12) NOT NULL DEFAULT ' ' ,
	LPPOLTYPE CHAR    (4) NOT NULL DEFAULT ' ' ,
	PROCESSFLG CHAR    (1) NOT NULL DEFAULT ' ' ,
	ENTRYDATE NUMERIC (8, 0) NOT NULL DEFAULT 0
);

CREATE TABLE MOVETRAIL
(
	MOVE_DOC_ID CHAR    (12) NOT NULL DEFAULT ' ' ,
	MOVE_CASE_ID CHAR    (9) NOT NULL DEFAULT ' ' ,
	MOVE_DATE NUMERIC (8, 0) NOT NULL DEFAULT 0
);

CREATE TABLE POLAUTOIS
(
	POLID CHAR    (11) NOT NULL DEFAULT ' ' ,
	AUTOISSFLG CHAR    (1) NOT NULL DEFAULT ' '
);

ALTER TABLE POLAUTOIS
ADD CONSTRAINT AK_POLID UNIQUE (POLID);

CREATE TABLE QCRUNHIS
(
	QCCASEID CHAR    (9) NOT NULL DEFAULT ' ' ,
	QCPOLID CHAR    (11) NOT NULL DEFAULT ' ' ,
	QCDOCTYPE CHAR    (8) NOT NULL DEFAULT ' ' ,
	QCUSERID CHAR    (8) NOT NULL DEFAULT ' ' ,
	QCREVIEWER CHAR    (8) NOT NULL DEFAULT ' ' ,
	QCQCPASS CHAR    (1) NOT NULL DEFAULT ' ' ,
	QCDATE NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
	QCTIME NUMERIC (8, 0) NOT NULL DEFAULT 0
);

CREATE TABLE STATEYES
(
	SYTEMPLATE CHAR    (10) NOT NULL DEFAULT ' ' ,
	SYSTATE CHAR    (2) NOT NULL DEFAULT ' '
);

CREATE TABLE TRNIDPOLR
(
	TPTRANSID CHAR    (10) NOT NULL DEFAULT ' ' ,
	TPPOLID CHAR    (11) NOT NULL DEFAULT ' ' ,
	TPCASEID CHAR    (9) NOT NULL DEFAULT ' ' ,
	TPSOURCE CHAR    (10) NOT NULL DEFAULT ' ' ,
	TPDATEIN NUMERIC (8, 0) NOT NULL DEFAULT 0
);

CREATE TABLE WRKQCRUN
(
	WRUSRID CHAR    (8) NOT NULL DEFAULT ' ' ,
	WRBARUNCNT NUMERIC (3, 0) NOT NULL DEFAULT 0 ,
	WRLTRUNCNT NUMERIC (3, 0) NOT NULL DEFAULT 0 ,
	WRIPRUNCNT NUMERIC (3, 0) NOT NULL DEFAULT 0 ,
	WRDRRUNCNT NUMERIC (3, 0) NOT NULL DEFAULT 0 ,
	WRGFRUNCNT NUMERIC (3, 0) NOT NULL DEFAULT 0 ,
	WRBERUNCNT NUMERIC (3, 0) NOT NULL DEFAULT 0
);

CREATE TABLE EMSITIFF
(
    TIFDOCID CHAR    (8) NOT NULL DEFAULT ' ' ,
    WAFDOCID CHAR    (12) NOT NULL DEFAULT ' ' ,
    POLICYID CHAR    (11) NOT NULL DEFAULT ' ' ,
    POLICYID1 CHAR    (11) NOT NULL DEFAULT ' ' ,
    PROCESSFLG CHAR    (1) NOT NULL DEFAULT ' ' ,
    PROCESSFG1 CHAR    (1) NOT NULL DEFAULT ' ' ,
    PROCESSTYP CHAR    (1) NOT NULL DEFAULT ' ' ,
    SNDTOEMSI CHAR    (1) NOT NULL DEFAULT ' ' ,
    XREFFLG CHAR    (1) NOT NULL DEFAULT ' ' ,
    ACKNOWLED CHAR    (1) NOT NULL DEFAULT ' ' ,
    ACKNOWLED1 CHAR    (1) NOT NULL DEFAULT ' ' ,
    JTISSFLG1 CHAR    (1) NOT NULL DEFAULT ' ' ,
    JTISSFLG2 CHAR    (1) NOT NULL DEFAULT ' ' ,
    PROCESSDAT NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
    PROCESSDT1 NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
    PROCESSTIM NUMERIC (8, 0) NOT NULL DEFAULT 0 ,
    PROCESSTM1 NUMERIC (8, 0) NOT NULL DEFAULT 0
);