-- noinspection SqlDialectInspectionForFile

CREATE TABLE ZIPCITY2
(
    ZIP2 NUMERIC (5, 0) NOT NULL DEFAULT 0 ,
    CITY2 CHAR    (28) NOT NULL DEFAULT ' '
);

CREATE TABLE ZIPCITY1
(
    ZIP1 NUMERIC (5, 0) NOT NULL DEFAULT 0 ,
    CITY1 CHAR    (28) NOT NULL DEFAULT ' '
);

CREATE TABLE STETBLP
(
    CRCPCD CHAR    (2) NOT NULL DEFAULT ' ' ,
    CRCOCD CHAR    (2) NOT NULL DEFAULT ' ' ,
    CRB6NA CHAR    (20) NOT NULL DEFAULT ' ' ,
    CRWRST CHAR    (1) NOT NULL DEFAULT ' '
);

CREATE TABLE APPSWTA
(
    A_HEIGHT CHAR    (3) NOT NULL DEFAULT ' ' ,
    A_HIGH_WEIGHT NUMERIC (3, 0) NOT NULL DEFAULT 0 ,
    A_LOW_WEIGHT NUMERIC (3, 0) NOT NULL DEFAULT 0
);

CREATE TABLE APPSWTC
(
    C_AGE NUMERIC (2, 0) NOT NULL DEFAULT 0 ,
    C_MONTH NUMERIC (2, 0) NOT NULL DEFAULT 0 ,
    C_SEX CHAR    (1) NOT NULL DEFAULT ' ' ,
    C_LOW_HEIGHT NUMERIC (3, 0) NOT NULL DEFAULT 0 ,
    C_HIGH_HEIGHT NUMERIC (3, 0) NOT NULL DEFAULT 0 ,
    C_LOW_WEIGHT NUMERIC (3, 0) NOT NULL DEFAULT 0 ,
    C_HIGH_WEIGHT NUMERIC (3, 0) NOT NULL DEFAULT 0
);