CREATE TABLE TSACORRHIS
( 
	TCDOCTYP CHAR    (8) NOT NULL DEFAULT ' ' ,
	TCDOCID CHAR    (12) NOT NULL DEFAULT ' ' ,
	TCSSN CHAR    (9) NOT NULL DEFAULT ' ' ,
	TCSCANDATE NUMERIC (8, 0) NOT NULL DEFAULT 0 
);

ALTER table TSACORRHIS add primary Key(TCDOCID);