CREATE TABLE [ERROR](
	[CODE] [varchar](9) NOT NULL,
	[MESSAGE] [varchar](1000) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY];


CREATE TABLE [EMAIL_TEMPLATE](
	[id] [int] NOT NULL,
	[EMAIL_BCC] [varchar](255) NULL,
	[EMAIL_CC] [varchar](255) NULL,
	[EMAIL_SUBJECT] [varchar](255) NOT NULL,
	[EMAIL_TO] [varchar](255) NOT NULL,
	[IS_ACTIVE] [bit] NOT NULL,
	[TEMPLATE_CONTENT] [varchar](max) NOT NULL,
	[TEMPLATE_NAME] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UK_TEMPLATE_NAME] UNIQUE NONCLUSTERED 
(
	[TEMPLATE_NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];


CREATE TABLE [dbo].[SHAREPOINT_CONTROL](
	[id] [int] NOT NULL IDENTITY(1,1),
	[counter] [int] NULL,
	[is_available] [bit] NULL,
	[library_id] [varchar](255) NULL,
	[library_name] [varchar](255) NULL,
	[site_id] [varchar](255) NULL,
	[site_name] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


