CREATE TABLE CORIMGPF
( 
	ACCTNO CHAR    (12) NOT NULL DEFAULT ' ' ,
	PAGENO NUMERIC (2, 0) NOT NULL DEFAULT 0 ,
	FILENAME CHAR    (12) NOT NULL DEFAULT ' ' ,
	DOCTYPE CHAR    (4) NOT NULL DEFAULT ' ' ,
	LETDESC CHAR    (50) NOT NULL DEFAULT ' ' 
);