CREATE TABLE LPISDIMGPF
( 
	ACCTNO CHAR    (12) NOT NULL DEFAULT ' ' ,
	PAGENO NUMERIC (2, 0) NOT NULL DEFAULT 0 ,
	FILENAME CHAR    (12) NOT NULL DEFAULT ' ' ,
	POLTYPE CHAR    (11) NOT NULL DEFAULT ' ' ,
	PTYPE CHAR    (1) NOT NULL DEFAULT ' ' ,
	ISSDT NUMERIC (8, 0) NOT NULL DEFAULT 0 
);
ALTER table LPISDIMGPF add primary Key(ACCTNO);
