---PRIMARY KEYS: NEW COLUMNS---
ALTER TABLE EKD0010 ADD ID bigint NOT NULL IDENTITY(1,1) PRIMARY KEY;
ALTER TABLE EKD0050 ADD ID bigint NOT NULL IDENTITY(1,1) PRIMARY KEY;
ALTER TABLE LPPOLNUM ADD ID bigint NOT NULL IDENTITY(1,1) PRIMARY KEY;


---SOFT DELETE: NEW COLUMNS---
ALTER TABLE EKD0110 ADD IS_DELETED int CONSTRAINT DF_EKD0110_IS_DELETED DEFAULT 0 NOT NULL;
ALTER TABLE EKD0150 ADD IS_DELETED int CONSTRAINT DF_EKD0150_IS_DELETED DEFAULT 0 NOT NULL;
ALTER TABLE EKD0210 ADD IS_DELETED int CONSTRAINT DF_EKD0210_IS_DELETED DEFAULT 0 NOT NULL;
ALTER TABLE EKD0250 ADD IS_DELETED int CONSTRAINT DF_EKD0250_IS_DELETED DEFAULT 0 NOT NULL;
ALTER TABLE EKD0260 ADD IS_DELETED int CONSTRAINT DF_EKD0260_IS_DELETED DEFAULT 0 NOT NULL;
ALTER TABLE EKD0310 ADD IS_DELETED int CONSTRAINT DF_EKD0310_IS_DELETED DEFAULT 0 NOT NULL;
ALTER TABLE EKD0315 ADD IS_DELETED int CONSTRAINT DF_EKD0315_IS_DELETED DEFAULT 0 NOT NULL;
ALTER TABLE EKD0350 ADD IS_DELETED int CONSTRAINT DF_EKD0350_IS_DELETED DEFAULT 0 NOT NULL;
ALTER TABLE EKD0352 ADD IS_DELETED int CONSTRAINT DF_EKD0352_IS_DELETED DEFAULT 0 NOT NULL;
ALTER TABLE EKD0353 ADD IS_DELETED int CONSTRAINT DF_EKD0353_IS_DELETED DEFAULT 0 NOT NULL;
ALTER TABLE EKD0360 ADD IS_DELETED int CONSTRAINT DF_EKD0360_IS_DELETED DEFAULT 0 NOT NULL;
ALTER TABLE EKD0370 ADD IS_DELETED int CONSTRAINT DF_EKD0370_IS_DELETED DEFAULT 0 NOT NULL;
ALTER TABLE EKD0850 ADD IS_DELETED int CONSTRAINT DF_EKD0850_IS_DELETED DEFAULT 0 NOT NULL;
ALTER TABLE EKDUSER ADD IS_DELETED int CONSTRAINT DF_EKDUSER_IS_DELETED DEFAULT 0 NOT NULL;
ALTER TABLE LPPOLNUM ADD IS_DELETED int CONSTRAINT DF_LPPOLNUM_IS_DELETED DEFAULT 0 NOT NULL;
ALTER TABLE PNDDOCTYP ADD IS_DELETED int CONSTRAINT DF_PNDDOCTYP_IS_DELETED DEFAULT 0 NOT NULL;