CREATE TABLE MEDRJT_CAUSE_CODES (
	CAUSE_CODE varchar(15) NOT NULL,
	CODE_TYPE varchar(3) NULL,
	DESCRIPTION varchar(300) NOT NULL
);
ALTER table MEDRJT_CAUSE_CODES add CONSTRAINT PK_MEDRJT_CAUSE_CODES primary Key(CAUSE_CODE);